<?php

namespace Smalot\Cups\Tags;

class AttributeGroup
{
    const OPERATION_ATTRIBUTES_TAG = 0x01;
    const JOB_ATTRIBUTES_TAG = 0x02;
    const END_OF_ATTRIBUTES_TAG = 0x03;
    const PRINTER_ATTRIBUTES_TAG = 0x04;
    const UNSUPPORTED_ATTRIBUTES_TAG = 0x05;
    const SUBSCRIPTION_ATTRIBUTES_TAG = 0x06;
    const EVENT_NOTIFICATION_ATTRIBUTES_TAG = 0x07;
    const RESOURCE_ATTRIBUTES_TAG = 0x08;
    const DOCUMENT_ATTRIBUTES_TAG = 0x09;
    const SYSTEM_ATTRIBUTES_TAG = 0x0A;

}
